#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAB34BA0040E92ECE (stevehay@apache.org)
#
Name     : mod_perl
Version  : 2.0.12
Release  : 17
URL      : https://www.apache.org/dist/perl/mod_perl-2.0.12.tar.gz
Source0  : https://www.apache.org/dist/perl/mod_perl-2.0.12.tar.gz
Source1  : https://www.apache.org/dist/perl/mod_perl-2.0.12.tar.gz.asc
Summary  : An embedded Perl interpreter for the Apache Web server
Group    : Development/Tools
License  : Apache-1.1 Apache-2.0
Requires: mod_perl-bin = %{version}-%{release}
Requires: mod_perl-lib = %{version}-%{release}
Requires: mod_perl-license = %{version}-%{release}
Requires: mod_perl-perl = %{version}-%{release}
Requires: perl(BSD::Resource)
Requires: perl(Data::Flow)
Requires: perl(Linux::Pid)
BuildRequires : apr-dev
BuildRequires : apr-util-dev
BuildRequires : buildreq-cpan
BuildRequires : gdbm-dev
BuildRequires : httpd-dev
BuildRequires : httpd-extras
Patch1: 0001-Fixup-installation-paths.patch

%description
Mod_perl incorporates a Perl interpreter into the Apache web server,
so that the Apache web server can directly execute Perl code.
Mod_perl links the Perl runtime library into the Apache web server and
provides an object-oriented Perl interface for Apache's C language
API.  The end result is a quicker CGI script turnaround process, since
no external Perl interpreter has to be started.

Install mod_perl if you're installing the Apache web server and you'd
like for it to directly incorporate a Perl interpreter.

%package bin
Summary: bin components for the mod_perl package.
Group: Binaries
Requires: mod_perl-license = %{version}-%{release}

%description bin
bin components for the mod_perl package.


%package dev
Summary: dev components for the mod_perl package.
Group: Development
Requires: mod_perl-lib = %{version}-%{release}
Requires: mod_perl-bin = %{version}-%{release}
Provides: mod_perl-devel = %{version}-%{release}
Requires: mod_perl = %{version}-%{release}

%description dev
dev components for the mod_perl package.


%package lib
Summary: lib components for the mod_perl package.
Group: Libraries
Requires: mod_perl-license = %{version}-%{release}

%description lib
lib components for the mod_perl package.


%package license
Summary: license components for the mod_perl package.
Group: Default

%description license
license components for the mod_perl package.


%package perl
Summary: perl components for the mod_perl package.
Group: Default
Requires: mod_perl = %{version}-%{release}

%description perl
perl components for the mod_perl package.


%prep
%setup -q -n mod_perl-2.0.12
cd %{_builddir}/mod_perl-2.0.12
%patch1 -p1

%build
## build_prepend content
# Exclude a conditional package defined in
# `Apache-Test/lib/Apache/TestRequest.pm`. The distro provider is the
# `perl-HTTP-Message` package.
%global __provides_exclude ^perl\\(HTTP::Request::Common\\)$

export MP_APR_CONFIG=/usr/bin/apr-1-config
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mod_perl
cp %{_builddir}/mod_perl-2.0.12/Apache-Reload/LICENSE %{buildroot}/usr/share/package-licenses/mod_perl/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/mod_perl-2.0.12/Apache-SizeLimit/LICENSE %{buildroot}/usr/share/package-licenses/mod_perl/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/mod_perl-2.0.12/Apache-Test/LICENSE %{buildroot}/usr/share/package-licenses/mod_perl/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/mod_perl-2.0.12/LICENSE %{buildroot}/usr/share/package-licenses/mod_perl/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/mod_perl-2.0.12/NOTICE %{buildroot}/usr/share/package-licenses/mod_perl/97c92650e1f9ce20b0b9e82b6effb9653f0d5541
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mp2bug

%files dev
%defattr(-,root,root,-)
/usr/include/httpd/mod_perl.h
/usr/include/httpd/modperl_apache_compat.h
/usr/include/httpd/modperl_apache_includes.h
/usr/include/httpd/modperl_apr_compat.h
/usr/include/httpd/modperl_apr_includes.h
/usr/include/httpd/modperl_apr_perlio.h
/usr/include/httpd/modperl_bucket.h
/usr/include/httpd/modperl_callback.h
/usr/include/httpd/modperl_cgi.h
/usr/include/httpd/modperl_cmd.h
/usr/include/httpd/modperl_common_includes.h
/usr/include/httpd/modperl_common_log.h
/usr/include/httpd/modperl_common_types.h
/usr/include/httpd/modperl_common_util.h
/usr/include/httpd/modperl_config.h
/usr/include/httpd/modperl_const.h
/usr/include/httpd/modperl_constants.h
/usr/include/httpd/modperl_debug.h
/usr/include/httpd/modperl_directives.h
/usr/include/httpd/modperl_env.h
/usr/include/httpd/modperl_error.h
/usr/include/httpd/modperl_filter.h
/usr/include/httpd/modperl_flags.h
/usr/include/httpd/modperl_global.h
/usr/include/httpd/modperl_gtop.h
/usr/include/httpd/modperl_handler.h
/usr/include/httpd/modperl_hooks.h
/usr/include/httpd/modperl_interp.h
/usr/include/httpd/modperl_io.h
/usr/include/httpd/modperl_io_apache.h
/usr/include/httpd/modperl_largefiles.h
/usr/include/httpd/modperl_log.h
/usr/include/httpd/modperl_mgv.h
/usr/include/httpd/modperl_module.h
/usr/include/httpd/modperl_options.h
/usr/include/httpd/modperl_pcw.h
/usr/include/httpd/modperl_perl.h
/usr/include/httpd/modperl_perl_global.h
/usr/include/httpd/modperl_perl_includes.h
/usr/include/httpd/modperl_perl_pp.h
/usr/include/httpd/modperl_perl_unembed.h
/usr/include/httpd/modperl_svptr_table.h
/usr/include/httpd/modperl_sys.h
/usr/include/httpd/modperl_time.h
/usr/include/httpd/modperl_tipool.h
/usr/include/httpd/modperl_trace.h
/usr/include/httpd/modperl_types.h
/usr/include/httpd/modperl_util.h
/usr/include/httpd/modperl_xs_sv_convert.h
/usr/include/httpd/modperl_xs_typedefs.h
/usr/include/httpd/modperl_xs_util.h
/usr/share/man/man3/APR.3
/usr/share/man/man3/APR::Base64.3
/usr/share/man/man3/APR::Brigade.3
/usr/share/man/man3/APR::Bucket.3
/usr/share/man/man3/APR::BucketAlloc.3
/usr/share/man/man3/APR::BucketType.3
/usr/share/man/man3/APR::Const.3
/usr/share/man/man3/APR::Date.3
/usr/share/man/man3/APR::Error.3
/usr/share/man/man3/APR::Finfo.3
/usr/share/man/man3/APR::IpSubnet.3
/usr/share/man/man3/APR::OS.3
/usr/share/man/man3/APR::PerlIO.3
/usr/share/man/man3/APR::Pool.3
/usr/share/man/man3/APR::SockAddr.3
/usr/share/man/man3/APR::Socket.3
/usr/share/man/man3/APR::Status.3
/usr/share/man/man3/APR::String.3
/usr/share/man/man3/APR::Table.3
/usr/share/man/man3/APR::ThreadMutex.3
/usr/share/man/man3/APR::ThreadRWLock.3
/usr/share/man/man3/APR::URI.3
/usr/share/man/man3/APR::UUID.3
/usr/share/man/man3/APR::Util.3
/usr/share/man/man3/Apache2::Access.3
/usr/share/man/man3/Apache2::Build.3
/usr/share/man/man3/Apache2::CmdParms.3
/usr/share/man/man3/Apache2::Command.3
/usr/share/man/man3/Apache2::Connection.3
/usr/share/man/man3/Apache2::ConnectionUtil.3
/usr/share/man/man3/Apache2::Const.3
/usr/share/man/man3/Apache2::Directive.3
/usr/share/man/man3/Apache2::Filter.3
/usr/share/man/man3/Apache2::FilterRec.3
/usr/share/man/man3/Apache2::HookRun.3
/usr/share/man/man3/Apache2::Log.3
/usr/share/man/man3/Apache2::MPM.3
/usr/share/man/man3/Apache2::Module.3
/usr/share/man/man3/Apache2::PerlSections.3
/usr/share/man/man3/Apache2::Process.3
/usr/share/man/man3/Apache2::Reload.3
/usr/share/man/man3/Apache2::RequestIO.3
/usr/share/man/man3/Apache2::RequestRec.3
/usr/share/man/man3/Apache2::RequestUtil.3
/usr/share/man/man3/Apache2::Resource.3
/usr/share/man/man3/Apache2::Response.3
/usr/share/man/man3/Apache2::ServerRec.3
/usr/share/man/man3/Apache2::ServerUtil.3
/usr/share/man/man3/Apache2::SizeLimit.3
/usr/share/man/man3/Apache2::Status.3
/usr/share/man/man3/Apache2::SubProcess.3
/usr/share/man/man3/Apache2::SubRequest.3
/usr/share/man/man3/Apache2::URI.3
/usr/share/man/man3/Apache2::Util.3
/usr/share/man/man3/Apache2::compat.3
/usr/share/man/man3/Apache2::porting.3
/usr/share/man/man3/Apache::Reload.3
/usr/share/man/man3/Apache::SizeLimit.3
/usr/share/man/man3/Apache::SizeLimit::Core.3
/usr/share/man/man3/Apache::Test.3
/usr/share/man/man3/Apache::TestConfig.3
/usr/share/man/man3/Apache::TestHandler.3
/usr/share/man/man3/Apache::TestMB.3
/usr/share/man/man3/Apache::TestMM.3
/usr/share/man/man3/Apache::TestReport.3
/usr/share/man/man3/Apache::TestRequest.3
/usr/share/man/man3/Apache::TestRun.3
/usr/share/man/man3/Apache::TestRunPHP.3
/usr/share/man/man3/Apache::TestRunPerl.3
/usr/share/man/man3/Apache::TestServer.3
/usr/share/man/man3/Apache::TestSmoke.3
/usr/share/man/man3/Apache::TestTrace.3
/usr/share/man/man3/Apache::TestUtil.3
/usr/share/man/man3/Bundle::Apache2.3
/usr/share/man/man3/Bundle::ApacheTest.3
/usr/share/man/man3/ModPerl::BuildMM.3
/usr/share/man/man3/ModPerl::CScan.3
/usr/share/man/man3/ModPerl::Code.3
/usr/share/man/man3/ModPerl::Config.3
/usr/share/man/man3/ModPerl::Const.3
/usr/share/man/man3/ModPerl::Global.3
/usr/share/man/man3/ModPerl::MM.3
/usr/share/man/man3/ModPerl::MethodLookup.3
/usr/share/man/man3/ModPerl::PerlRun.3
/usr/share/man/man3/ModPerl::PerlRunPrefork.3
/usr/share/man/man3/ModPerl::Registry.3
/usr/share/man/man3/ModPerl::RegistryBB.3
/usr/share/man/man3/ModPerl::RegistryCooker.3
/usr/share/man/man3/ModPerl::RegistryLoader.3
/usr/share/man/man3/ModPerl::RegistryPrefork.3
/usr/share/man/man3/ModPerl::Util.3
/usr/share/man/man3/mod_perl2.3

%files lib
%defattr(-,root,root,-)
/usr/lib/httpd/modules/mod_perl.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mod_perl/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/mod_perl/97c92650e1f9ce20b0b9e82b6effb9653f0d5541

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
